### PR TITLE
Feature/menu music player controls

### PR DESCRIPTION
**Pull request by p0psicles**

### CODE REVIEW

**Comment by damianodonoghue** [comment]
I have updated the requested features audio and subs settings.Just wondering how best to proceed (Sorry new to github) Should I select the branch Feature/menu music player controls and then do a new PR? I don't seem to be edit the new branch direct. Thanks!

**Comment by p0psicles** [comment]
You pull branches from this fork to yours. Then checkout this branch in your repo. Make the changes and create a Pr against this branch.

**Comment by p0psicles** [comment]
A little tip. To be able to work your fork and on this project. you can add two origins.
One you can just name `origin` which point's to your own fork. And then you can add an `upstream` repo.
More info here:
https://help.github.com/articles/configuring-a-remote-for-a-fork/

That way you can check out this `feature/menu-music-player-controls`, make changes to it locally, and then push it back to `origin` (not upstream where you got it from).

Now you can use github to create the PR from `github.com/damianodonoghue/GoogleHomeKodi/tree/feature/menu-music-player-controls` to `github.com/OmerTu/GoogleHomeKodi/tree/feature/menu-music-player-controls`.

**Comment by p0psicles** [comment]
@damianodonoghue did some eslinting.
Also merged latest changes from develop into this branch.
Can you rerun your tests one more time?

**Pull request merged**
