### PR TITLE
Added StandBy command to turn off TV via HDMI-CEC

### PR DESCRIPTION
**Pull request by mikerosile**

### CODE REVIEW

**Comment by keydon** [comment]
thanks for your contribution.

but please re-request a pull onto the develop branch.
I tried to rebase your commit onto the develop branch via the github gui. but i failed miserably. So please do it on your end.

**Comment by keydon** [comment]
ah one more thing. please also add your new endpoint to the [full table with available actions](https://github.com/OmerTu/GoogleHomeKodi#full-table-with-available-actions)

**Comment by keydon** [comment]
you seem to have reverted some changes in the readme from your previous commit by accident. like the _on/off_ change.

**Comment by keydon** [comment]
and you are still targeting the master branch.

**Comment by mikerosile** [comment]
Please close this pull request, I created a new one pointing to the Develop branch.

**Comment by keydon** [comment]
as you wish :)

**Pull request closed without merging**
